export const CHAT_WIDGET_SELECTORS: readonly string[] = [
  "#hubspot-messages-iframe-container",
  "#hubspot-conversations-iframe",
  "#intercom-container",
  ".intercom-lightweight-app",
  ".intercom-app",
  "#drift-frame-controller",
  "#drift-frame-chat",
  "#drift-widget-container",
  "#crisp-chatbox",
  ".crisp-client",
  "#tidio-chat",
  "#tawkchat-container",
  "iframe[title='chat widget']",
  "iframe[title='Chat widget']",
  "iframe[title='Chat Widget']",
  "iframe[title='Chat Window']",
  "iframe[title='Chat Launcher']",
];
